### ISSUE TITLE
It's not an issue

### ISSUE THREAD

**Issue by bartashevich** [bartashevich/VBA#1]
Привет Павел,
Меня зовут Денис Барташевич, и я хотел бы изменить свое имя пользователя GitHub на "Барташевич", но вы используете его. Может быть, если вы не используете свой счет GitHub вы могли бы помочь мне с этим.

Простите за вопрос.
С наилучшими пожеланиями.

**Comment by bartashevich-pavel** [comment]
Добрый день, Денис.
Да, я не использую свой аккаунт и, в принципе, мне не сложно передать вам данный логин.
Какие от меня требуются действия?

Павел

**Comment by bartashevich** [comment]
Спасибо, вам просто нужно зайти в опции и изменить имя пользователя на другой.

https://help.github.com/articles/changing-your-github-username/

**Comment by bartashevich-pavel** [comment]
Готово, Денис.
Пользуйтесь на здоровье.
Удачи.
